// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvtcqJmx0BwOBE31BtKuoLQxRNc2RAqZ8',
    appId: '1:945880757096:web:4d59faacecbda03e3bdcdd',
    messagingSenderId: '945880757096',
    projectId: 'stay-match-715a6',
    authDomain: 'stay-match-715a6.firebaseapp.com',
    storageBucket: 'stay-match-715a6.firebasestorage.app',
    measurementId: 'G-VW3S5ZFS95',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV69srG3FftafUOfnNubgWqWQp1-R2mtw',
    appId: '1:945880757096:android:433fec2991d714413bdcdd',
    messagingSenderId: '945880757096',
    projectId: 'stay-match-715a6',
    storageBucket: 'stay-match-715a6.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvtcqJmx0BwOBE31BtKuoLQxRNc2RAqZ8',
    appId: '1:945880757096:web:11df5a499b2083003bdcdd',
    messagingSenderId: '945880757096',
    projectId: 'stay-match-715a6',
    authDomain: 'stay-match-715a6.firebaseapp.com',
    storageBucket: 'stay-match-715a6.firebasestorage.app',
    measurementId: 'G-G8MGD3QFN1',
  );
}
